name: Tests
on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: true
      - run: cat "${GITHUB_WORKSPACE}/.github/env.properties" >> $GITHUB_ENV

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"

      - name: Dependencies cache
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: "./node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('./package-lock.json') }}

      - name: Hardhat Cache
        uses: actions/cache@v2
        id: hardhat-cache
        with:
          path: "./cache"
          key: ${{ runner.os }}-build-${{ hashFiles('./contracts/**') }}

      - name: Run npm install
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm i

      - name: Run npm test
        run: npm t
